version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/backend/nyaysetu-backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "fix"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/frontend/nyaysetu-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/nlp-orchestrator"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "ci"
      - "dependencies"