### Create Case
POST http://localhost:8082/cases
Content-Type: application/json

{
  "title": "Demo Case",
  "description": "Testing full workflow",
  "judgeId": "11111111-1111-1111-1111-111111111111",
  "parties": [
    { "name": "Virendra", "role": "PLAINTIFF" },
    { "name": "Opponent", "role": "DEFENDANT" }
  ]
}

### Get All Cases
GET http://localhost:9000/cases

### Schedule Hearing
POST http://localhost:8082/cases/16b99ca4-3ff4-4b7f-b5d5-e4f05fbf437b/hearings
Content-Type: application/json

{
  "when": "2025-12-30T10:30:00",
  "location": "Court Hall A",
  "notes": "Initial appearance"
}

### Add Note
POST http://localhost:8082/cases/16b99ca4-3ff4-4b7f-b5d5-e4f05fbf437b/notes
Content-Type: application/json

{
  "content": "Judge reviewed all documents",
  "authorId": "22222222-2222-2222-2222-222222222222"
}

### Upload Evidence
POST http://localhost:8082/cases/16b99ca4-3ff4-4b7f-b5d5-e4f05fbf437b/evidence/upload
Content-Type: multipart/form-data

file=@/Users/virendragadekar/Documents/sample.pdf
uploaderId: 33333333-3333-3333-3333-333333333333

### Send Message
POST http://localhost:8082/cases/16b99ca4-3ff4-4b7f-b5d5-e4f05fbf437b/messages
Content-Type: application/json

{
  "senderId": "11111111-1111-1111-1111-111111111111",
  "message": "Hello, update the status."
}

### Get Timeline
GET http://localhost:8082/cases/16b99ca4-3ff4-4b7f-b5d5-e4f05fbf437b/timeline


### Create Case
POST http://localhost:9000/cases
Content-Type: application/json

{
  "title": "Gateway Test Case",
  "description": "Testing via gateway",
  "judgeId": "11111111-1111-1111-1111-111111111111",
  "parties": [
    { "name": "Virendra", "role": "PLAINTIFF" },
    { "name": "Opponent", "role": "DEFENDANT" }
  ]
}

###

POST http://localhost:9000/cases/10e2d6ad-0345-4127-98cc-b00ac58835dd/hearings
Content-Type: application/json

{
"when": "2025-12-30T10:30:00",
"location": "Court Hall A",
"notes": "Initial appearance"
}

###
POST http://localhost:9000/cases/10e2d6ad-0345-4127-98cc-b00ac58835dd/notes
Content-Type: application/json

{
  "content": "Judge reviewed all documents",
  "authorId": "22222222-2222-2222-2222-222222222222"
}

###
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "email": "admin@nyay.com",
  "password": "password"
}