package com.nyaysetu.backend.entity;

public enum CaseStatus {
    PENDING,
    OPEN,
    IN_PROGRESS,
    UNDER_REVIEW,
    AWAITING_DOCUMENTS,
    COMPLETED,
    CLOSED,
    ON_HOLD,
    FIR_FILED,
    PENDING_COGNIZANCE,
    COGNIZANCE_PERIOD,
    SUMMONS_SERVED,
    DRAFT_PENDING_CLIENT,
    READY_FOR_COURT,
    APPROVED
}
