import { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import {
    ArrowLeft, FileText, Calendar, User, Scale, Clock,
    Download, AlertCircle, CheckCircle, Loader2,
    Gavel, FileCheck, MessageSquare
} from 'lucide-react';
import { caseAPI, documentAPI } from '../../services/api';
import CaseChatWidget from '../../components/CaseChatWidget';

const statusColors = {
    'PENDING': { bg: '#f5930020', border: '#f59e0b', text: '#f59e0b' },
    'IN_PROGRESS': { bg: '#3b82f620', border: '#3b82f6', text: '#3b82f6' },
    'UNDER_REVIEW': { bg: '#8b5cf620', border: '#8b5cf6', text: '#8b5cf6' },
    'AWAITING_DOCUMENTS': { bg: '#ef444420', border: '#ef4444', text: '#ef4444' },
    'COMPLETED': { bg: '#10b98120', border: '#10b981', text: '#10b981' },
    'CLOSED': { bg: '#64748b20', border: '#64748b', text: '#64748b' }
};

const urgencyColors = {
    'NORMAL': { bg: '#10b98120', text: '#10b981' },
    'URGENT': { bg: '#f5930020', text: '#f59e0b' },
    'CRITICAL': { bg: '#ef444420', text: '#ef4444' }
};

export default function CaseDetailPage() {
    const { caseId } = useParams();
    const navigate = useNavigate();
    const [caseData, setCaseData] = useState(null);
    const [documents, setDocuments] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        fetchCaseDetails();
        fetchDocuments();
    }, [caseId]);

    const fetchCaseDetails = async () => {
        setLoading(true);
        try {
            const response = await caseAPI.getById(caseId);
            setCaseData(response.data);
            setError(null);
        } catch (err) {
            console.error('Error fetching case:', err);
            setError('Failed to load case details');
        } finally {
            setLoading(false);
        }
    };

    const fetchDocuments = async () => {
        try {
            const response = await documentAPI.getByCase(caseId);
            setDocuments(response.data || []);
        } catch (err) {
            console.error('Error fetching documents:', err);
            // Don't set error state - documents are optional
        }
    };

    const downloadDocument = async (doc) => {
        try {
            const response = await documentAPI.download(doc.id);
            const blob = new Blob([response.data], { type: doc.contentType || 'application/octet-stream' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = doc.fileName || 'document';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        } catch (err) {
            console.error('Error downloading document:', err);
            alert('Failed to download document');
        }
    };

    const downloadCase = async () => {
        // For now, generate a simple text download
        const caseText = `
NYAY-SETU CASE DOCUMENT
========================

Case ID: ${caseData.id}
Title: ${caseData.title}
Case Type: ${caseData.caseType}
Status: ${caseData.status}
Urgency: ${caseData.urgency}

PARTIES:
- Petitioner: ${caseData.petitioner}
- Respondent: ${caseData.respondent}

DETAILS:
${caseData.description}

Filed Date: ${caseData.filedDate ? new Date(caseData.filedDate).toLocaleDateString() : 'N/A'}
Assigned Judge: ${caseData.assignedJudge || 'Not assigned'}
Next Hearing: ${caseData.nextHearing ? new Date(caseData.nextHearing).toLocaleDateString() : 'To be scheduled'}

AI SUMMARY:
${caseData.aiGeneratedSummary || 'No AI summary available'}

---
Generated by NyaySetu Digital Judiciary Platform
        `.trim();

        const blob = new Blob([caseText], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `case-${caseData.id}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const formatDate = (dateString) => {
        if (!dateString) return 'N/A';
        return new Date(dateString).toLocaleDateString('en-IN', {
            day: 'numeric', month: 'short', year: 'numeric'
        });
    };

    if (loading) {
        return (
            <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '400px' }}>
                <Loader2 size={48} style={{ color: '#8b5cf6', animation: 'spin 1s linear infinite' }} />
                <style>{`@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
            </div>
        );
    }

    if (error || !caseData) {
        return (
            <div style={{ textAlign: 'center', padding: '3rem' }}>
                <AlertCircle size={64} style={{ color: '#ef4444', marginBottom: '1rem' }} />
                <h2 style={{ color: 'var(--text-main)' }}>{error || 'Case not found'}</h2>
                <button onClick={() => navigate('/client/cases')} style={{
                    marginTop: '1rem', padding: '0.75rem 1.5rem',
                    background: 'linear-gradient(135deg, var(--color-accent), var(--color-accent-hover))',
                    border: 'none', borderRadius: '0.5rem', color: 'white', cursor: 'pointer'
                }}>Back to My Cases</button>
            </div>
        );
    }

    const statusStyle = statusColors[caseData.status] || statusColors['PENDING'];
    const urgencyStyle = urgencyColors[caseData.urgency] || urgencyColors['NORMAL'];

    return (
        <div>
            {/* Header */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                    <button onClick={() => navigate('/client/cases')} style={{
                        background: 'var(--bg-glass)',
                        border: 'var(--border-glass)',
                        borderRadius: '0.5rem', padding: '0.5rem',
                        cursor: 'pointer', color: 'var(--color-accent)', display: 'flex', alignItems: 'center'
                    }}><ArrowLeft size={20} /></button>
                    <div>
                        <h1 style={{ fontSize: '1.75rem', fontWeight: '800', color: 'var(--text-main)', marginBottom: '0.25rem' }}>
                            Case Details
                        </h1>
                        <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
                            Case ID: {caseData.id?.toString().substring(0, 13)}...
                        </p>
                    </div>
                </div>
                <button onClick={downloadCase} style={{
                    display: 'flex', alignItems: 'center', gap: '0.5rem',
                    padding: '0.75rem 1.25rem',
                    background: 'linear-gradient(135deg, #10b981, #059669)',
                    border: 'none', borderRadius: '0.75rem', color: 'white',
                    fontWeight: '600', cursor: 'pointer',
                    boxShadow: 'var(--shadow-glass)'
                }}><Download size={18} /> Download Case</button>
            </div>

            {/* Status & Urgency Badges */}
            <div style={{ display: 'flex', gap: '1rem', marginBottom: '1.5rem' }}>
                <span style={{
                    padding: '0.5rem 1rem', borderRadius: '9999px',
                    background: statusStyle.bg, border: `1px solid ${statusStyle.border}`,
                    color: statusStyle.text, fontWeight: '600'
                }}>{caseData.status?.replace(/_/g, ' ')}</span>
                <span style={{
                    padding: '0.5rem 1rem', borderRadius: '9999px',
                    background: urgencyStyle.bg, color: urgencyStyle.text, fontWeight: '600'
                }}>⚡ {caseData.urgency}</span>
            </div>

            {/* Main Info Card */}
            <div style={{
                background: 'var(--bg-glass-strong)',
                border: 'var(--border-glass-strong)',
                borderRadius: '1.5rem', padding: '2rem', marginBottom: '1.5rem',
                boxShadow: 'var(--shadow-glass)'
            }}>
                <h2 style={{ fontSize: '1.5rem', fontWeight: '700', color: 'var(--text-main)', marginBottom: '1rem' }}>
                    {caseData.title}
                </h2>
                <p style={{ fontSize: '1rem', color: 'var(--text-secondary)', lineHeight: '1.6', marginBottom: '1.5rem' }}>
                    {caseData.description}
                </p>

                {/* Info Grid */}
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1.5rem' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                        <div style={{ padding: '0.75rem', background: 'rgba(139, 92, 246, 0.1)', borderRadius: '0.75rem' }}>
                            <FileText size={20} style={{ color: 'var(--color-accent)' }} />
                        </div>
                        <div>
                            <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Case Type</p>
                            <p style={{ fontSize: '1rem', fontWeight: '600', color: 'var(--text-main)' }}>{caseData.caseType}</p>
                        </div>
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                        <div style={{ padding: '0.75rem', background: 'rgba(16, 185, 129, 0.1)', borderRadius: '0.75rem' }}>
                            <Calendar size={20} style={{ color: '#10b981' }} />
                        </div>
                        <div>
                            <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Filed Date</p>
                            <p style={{ fontSize: '1rem', fontWeight: '600', color: 'var(--text-main)' }}>{formatDate(caseData.filedDate)}</p>
                        </div>
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                        <div style={{ padding: '0.75rem', background: 'rgba(245, 158, 11, 0.1)', borderRadius: '0.75rem' }}>
                            <Gavel size={20} style={{ color: '#f59e0b' }} />
                        </div>
                        <div>
                            <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Assigned Judge</p>
                            <p style={{ fontSize: '1rem', fontWeight: '600', color: 'var(--text-main)' }}>{caseData.assignedJudge || 'Not assigned'}</p>
                        </div>
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                        <div style={{ padding: '0.75rem', background: 'rgba(239, 68, 68, 0.1)', borderRadius: '0.75rem' }}>
                            <Clock size={20} style={{ color: '#ef4444' }} />
                        </div>
                        <div>
                            <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Next Hearing</p>
                            <p style={{ fontSize: '1rem', fontWeight: '600', color: 'var(--text-main)' }}>{formatDate(caseData.nextHearing) || 'To be scheduled'}</p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Parties Card */}
            <div style={{
                display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '1.5rem', marginBottom: '1.5rem'
            }}>
                <div style={{
                    background: 'var(--bg-glass)',
                    border: 'var(--border-glass)',
                    borderRadius: '1rem', padding: '1.5rem'
                }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.75rem' }}>
                        <User size={18} style={{ color: '#10b981' }} />
                        <h3 style={{ fontSize: '1rem', fontWeight: '600', color: '#10b981' }}>Petitioner</h3>
                    </div>
                    <p style={{ fontSize: '1.1rem', color: 'var(--text-main)', fontWeight: '500' }}>{caseData.petitioner}</p>
                </div>
                <div style={{
                    background: 'var(--bg-glass)',
                    border: 'var(--border-glass)',
                    borderRadius: '1rem', padding: '1.5rem'
                }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.75rem' }}>
                        <Scale size={18} style={{ color: '#ef4444' }} />
                        <h3 style={{ fontSize: '1rem', fontWeight: '600', color: '#ef4444' }}>Respondent</h3>
                    </div>
                    <p style={{ fontSize: '1.1rem', color: 'var(--text-main)', fontWeight: '500' }}>{caseData.respondent}</p>
                </div>
            </div>

            {/* AI Summary Card */}
            {caseData.aiGeneratedSummary && (
                <div style={{
                    background: 'linear-gradient(135deg, rgba(139, 92, 246, 0.05), rgba(99, 102, 241, 0.05))',
                    border: '1px solid rgba(139, 92, 246, 0.2)',
                    borderRadius: '1rem', padding: '1.5rem', marginBottom: '1.5rem',
                    backdropFilter: 'var(--glass-blur)'
                }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
                        <MessageSquare size={20} style={{ color: 'var(--color-accent)' }} />
                        <h3 style={{ fontSize: '1.1rem', fontWeight: '700', color: 'var(--color-accent)' }}>AI Case Summary</h3>
                    </div>
                    <pre style={{
                        color: 'var(--text-main)', fontSize: '0.9rem', lineHeight: '1.6',
                        whiteSpace: 'pre-wrap', fontFamily: 'inherit', margin: 0
                    }}>{caseData.aiGeneratedSummary}</pre>
                </div>
            )}

            {/* Attached Documents Section */}
            <div style={{
                background: 'var(--bg-glass-strong)',
                border: 'var(--border-glass-strong)',
                borderRadius: '1rem', padding: '1.5rem', marginBottom: '1.5rem',
                boxShadow: 'var(--shadow-glass)'
            }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
                    <FileCheck size={20} style={{ color: 'var(--color-accent)' }} />
                    <h3 style={{ fontSize: '1.1rem', fontWeight: '700', color: 'var(--text-main)' }}>
                        Attached Documents ({documents.length})
                    </h3>
                </div>

                {documents.length === 0 ? (
                    <div style={{
                        textAlign: 'center',
                        padding: '2rem',
                        color: 'var(--text-secondary)',
                        background: 'var(--bg-glass)',
                        borderRadius: '0.75rem',
                        border: 'var(--border-glass)'
                    }}>
                        <FileText size={32} style={{ color: 'var(--text-muted)', marginBottom: '0.5rem' }} />
                        <p style={{ margin: 0 }}>No documents attached to this case yet.</p>
                        <p style={{ margin: '0.5rem 0 0', fontSize: '0.85rem' }}>
                            You can upload documents from the Documents section.
                        </p>
                    </div>
                ) : (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                        {documents.map((doc) => (
                            <div
                                key={doc.id}
                                style={{
                                    display: 'flex',
                                    alignItems: 'center',
                                    justifyContent: 'space-between',
                                    padding: '1rem',
                                    background: 'var(--bg-glass)',
                                    borderRadius: '0.75rem',
                                    border: 'var(--border-glass)'
                                }}
                            >
                                <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                                    <div style={{
                                        width: '40px',
                                        height: '40px',
                                        borderRadius: '8px',
                                        background: 'rgba(139, 92, 246, 0.15)',
                                        display: 'flex',
                                        alignItems: 'center',
                                        justifyContent: 'center'
                                    }}>
                                        <FileText size={20} style={{ color: 'var(--color-accent)' }} />
                                    </div>
                                    <div>
                                        <p style={{
                                            fontSize: '0.95rem',
                                            fontWeight: '600',
                                            color: 'var(--text-main)',
                                            margin: 0
                                        }}>
                                            {doc.fileName}
                                        </p>
                                        <p style={{
                                            fontSize: '0.8rem',
                                            color: 'var(--text-secondary)',
                                            margin: '0.25rem 0 0'
                                        }}>
                                            {doc.category || 'Document'} • {doc.fileSize ? `${(doc.fileSize / 1024).toFixed(1)} KB` : 'Unknown size'}
                                        </p>
                                    </div>
                                </div>
                                <button
                                    onClick={() => downloadDocument(doc)}
                                    style={{
                                        display: 'flex',
                                        alignItems: 'center',
                                        gap: '0.5rem',
                                        padding: '0.5rem 1rem',
                                        background: 'rgba(16, 185, 129, 0.15)',
                                        border: '1px solid rgba(16, 185, 129, 0.3)',
                                        borderRadius: '0.5rem',
                                        color: '#10b981',
                                        cursor: 'pointer',
                                        fontWeight: '500',
                                        fontSize: '0.85rem'
                                    }}
                                >
                                    <Download size={16} /> Download
                                </button>
                            </div>
                        ))}
                    </div>
                )}
            </div>

            {/* Next Steps Card */}
            <div style={{
                background: 'rgba(16, 185, 129, 0.1)',
                border: '1px solid rgba(16, 185, 129, 0.3)',
                borderRadius: '1rem', padding: '1.5rem'
            }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
                    <CheckCircle size={20} style={{ color: '#10b981' }} />
                    <h3 style={{ fontSize: '1.1rem', fontWeight: '700', color: '#10b981' }}>Next Steps</h3>
                </div>
                <ul style={{ color: 'var(--text-main)', fontSize: '0.95rem', lineHeight: '1.8', paddingLeft: '1.5rem', margin: 0 }}>
                    <li>Gather all evidence documents (photos, CCTV footage, witness statements)</li>
                    <li>Upload documents to the Documents section</li>
                    <li>Wait for hearing date notification from the assigned judge</li>
                    <li>Prepare a brief statement of facts for the first hearing</li>
                </ul>
            </div>
            {/* Case Assistance Widget */}
            <CaseChatWidget caseId={caseId} caseTitle={caseData.title} />
        </div>
    );
}
