ALTER TABLE ny_user ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE ny_user ADD COLUMN IF NOT EXISTS is_oauth BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ny_user ADD COLUMN IF NOT EXISTS oauth_provider VARCHAR(50);
