name: PR Size Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label-pr-size:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Size Labeler
        uses: pascalgn/size-label-action@v0.5.5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          IGNORED_FILES: "package-lock.json,pom.xml,*.png,*.jpg"
